### ISSUE TITLE
Same bug

### ISSUE THREAD

**Issue by eltonfabricio10** [CudaText-addons/cuda_bulma_complete#1]
The cuda_bulma_complete plugin has the same bug as the cuda_bootstrap_complete:
https://github.com/halfbrained/cuda_bootstrap_complete/issues/21

**Comment by Alexey-T** [comment]
Is this OK for you if I disable multi-carets support in plugin?
Make this fix and test, pls:
file `__init__.py`,
add one line:
```
    def on_complete(self, ed_self):
        """ shows completion dialog: `ed_self.complete_alt()`
        """
        pass;       LOG and print(f'- bulma compelte')
        carets = ed_self.get_carets()
        if len(carets) != 1: return
```

**Comment by eltonfabricio10** [comment]
I added this to cuda_bootstrap_complete too
Thanks! :+1:
