### ISSUE TITLE
Class definition update

### ISSUE THREAD

**Issue by TomBraider42** [CudaText-addons/cuda_bulma_complete#2]
I have expanded and repaired the class definition file.
E.g. `button.is-black` doesn't work, changed to `button is-black`.
[completion_db.zip](https://github.com/CudaText-addons/cuda_bulma_complete/files/8139668/completion_db.zip)

Also i changed the `install.inf`:
`lexers=regex:HTML.*` to `lexers=regex:HTML.*|PHP`

**Comment by CudaText-addons** [comment]
applied. will update the plugin today.
